### PR TITLE
Updated onWebAppNameClick to read secure formData from correct json node

### PR DESCRIPTION
**Pull request by dskcode**
The Edit Web Apps dialog is not displaying the Secure value correctly.
The value in the database is set correctly, but on retrieval is being displayed incorrectly.

### CODE REVIEW

**Comment by jmahmoodcc** [comment]
Good find!
Can you add a test Selenium test as well which would have prevented this to begin with: https://github.com/cerner/jwala/blob/master/jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/manageWebApp.feature

**Comment by dskcode** [comment]
I am working on the selenium test, have to do env setup for the same on one of the spare 2016 server.

**Comment by dskcode** [comment]
@jmahmoodcc I have added selenium test cases please review the same and merge the changes if it looks good,

**Review by jmahmoodcc — APPROVED** [review]
Looks good!

**Pull request merged**
